---
- hosts: host
  become: True
  vars_prompt:
    - name: confirmation
      prompt: "Are you sure you want to reboot the system? Y/N: "
      private: false

  roles:
    - role: upgrade

    - role: reboot
      when: confirmation == "Y"
