---
- name: Install dnf
  yum:
    name: dnf
    state: latest

- name: Enable EPEL repository
  dnf:
    name: epel-release
    state: latest

- name: Upgrade all packages, excluding those indicated
  yum:
    name: "*"
    state: latest
    exclude:
      - "{{ r-pkg1 }}*"
      - "{{ r-pkg2 }}*"
      - "{{ r-pkg3 }}*"
      - "{{ r-pkg4 }}*"
      - "{{ r-pkg5 }}*"
      - "{{ r-pkg6 }}*"
      - "{{ r-pkg7 }}*"
      - "{{ r-pkg8 }}*"
      - "{{ r-pkg9 }}*"
      - "{{ r-pkg10 }}*"

- include_tasks: reboot.yml
  when: confirmation == "Y"
