---
- name: Reboot system
  command: reboot
  async: 60
  poll: 0
  register: status

- debug:
    msg: "System is rebooting..."

- wait_for_connection:
    delay: 1
    timeout: 300

- debug:
    msg: "The system has been rebooted"
