---
- name: Prevent packages from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)

- name: Update cache
  apt:
    update_cache: yes

- name: Upgrade all packages, excluding those indicated
  apt:
    name: "*"
    state: latest

- debug:
    msg: "{{ item }} not upgraded"
  with_items: "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)

- name: Allow packages to be upgraded again
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)
