---
- name: Debian - Prevent packages from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)

- name: Debian - Update cache
  apt:
    update_cache: yes

- name: Debian - Upgrade all packages, excluding those indicated
  apt:
    name: "*"
    state: latest

- debug: Debian
    msg: "{{ item }} not upgraded"
  with_items: "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)

- name: Debian - Allow packages to be upgraded again
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - "{{ deb_pkgs }}"
  when: deb_pkgs | default("null", false)
